name: Run Node.js (Test) Script Daily

on:
  schedule:
    - cron: "0 23 * * *" # Runs by 11 PM UTC
    - cron: "0 7 * * *" # Runs at 7 AM UTC
    - cron: "0 14 * * *" # Runs at 2 PM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (if needed)
        run: npm install # Skip this if your script doesn't need dependencies

      - name: Run the Script
        run: node script.js
